---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - http://hof.cluster.embl.de/conda-forge
  - http://hof.cluster.embl.de/bioconda
dependencies:
  - bioconda::diamond=2.1.12
  - python
